Homework4
Fullstack-Alfanar/malek-s-homework pull request #3
Opened 2022-04-12 13:40 UTC by MalekSafory

Validations homework
sorry for being late :)

2022-04-12 19:06 UTC, EliasSalom requested changes
after reviewing the js file I have been put some commitments on the file changed all the issues and pushed the new code

2022-04-12 19:06 UTC, EliasSalom commented on hw4/js/javas.js
> +function checkName(name) {
very complex function, please review the function and write it again!!

2022-04-12 19:06 UTC, EliasSalom commented on hw4/js/javas.js
> +function checkId(id) {
the function is not working will, please fix the function

2022-04-13 14:34 UTC, MalekSafory commented on hw4/js/javas.js
> +function checkName(name) {
i have rewrote it with simpler code

2022-04-13 14:54 UTC, EliasSalom requested changes
please check my comments

2022-04-13 14:54 UTC, EliasSalom commented on hw4/js/javas.js
> +    let arr = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k",
please check this line, this is what make all the functions complex, please change it or use it in different way

2022-04-13 15:00 UTC, MalekSafory commented on hw4/js/javas.js
> +    let arr = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k",
done , i have changed the function and made it more simple

2022-04-16 22:49 UTC, EliasSalom approved these changes
Good work

2022-04-16 22:49 UTC, merged